### ISSUE TITLE
[Test] SSE 테스트

### ISSUE THREAD

**Issue by fkthfvk112** [fkthfvk112/pick-fresh24#1]
## Description 🗞️📕
이전 버전에서 팀원이 SSE에서 에러가 발생한다고 알렸으나, 에러 로그가 없으며 에러 조건을 확실히 하지 않았다.
멀티 스레드 환경에서 SSE를 작동시키고 에러로그를 확인한다.

이를 위한 테스트 코드를 작성한다.

## To-Do ✔️
- [ ] 싱글 스레드로 테스트 코드 작성 및 통과
- [ ] 멑리 스레드로 테스트 코드 작성
- [ ] 에러 로그 확인 및 트러블 슈팅
